name: Deploy Website

on:
  push:
    branches:
      - main   # כל push ל-main יפעיל את הפייפליין

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'  # מעלה את כל הקבצים מה-root של הריפו

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
